### ISSUE TITLE
Hardcoded value for the duration of Storm local topology execution

### ISSUE THREAD

**Issue by arinto** [yahoo/samoa#109]
In Storm local mode, the topology always executes for at most 10 minutes.
Refer to `com.yahoo.labs.samoa.LocalStormDoTask` line [72]([https://github.com/yahoo/samoa/blob/master/samoa-storm/src/main/java/com/yahoo/labs/samoa/LocalStormDoTask.java#L72).

Possible solutions:
- Add a new option to determine local topology execution duration in `bin\samoa-storm.properties`, use `bin\samoa` to parse the new option and pass to `LocalStormDoTask` as program argument.
- Add the same new option as solution 1, use commons-configuration package to parse `bin\samoa-storm.properties`.

**Comment by gdfm** [comment]
Ported to [SAMOA-29](https://issues.apache.org/jira/browse/SAMOA-29).
