### ISSUE TITLE
i can not find a properties file, the name is src/resources/samoa-storm-cluster.properties,help me please.

### ISSUE THREAD

**Issue by wangchunli** [yahoo/samoa#111]
this file locates in samoa-storm,i find something where i can not understand,here is the code in  /src/com/yahoo/labs/samoa/topology/impl/StormSamoaUtils.java.
File f = new File("src/resources/samoa-storm-cluster.properties"); // FIXME it does not exist anymore
should i just remove  codes like this?

**Comment by gdfm** [comment]
Ported to [SAMOA-30](https://issues.apache.org/jira/browse/SAMOA-30).
