### ISSUE TITLE
Reformat codebase, add formatting guidelines

### ISSUE THREAD

**Issue by matthieumorel** [yahoo/samoa#118]
In the absence of a standard, the codebase has wrong indentation in quite a few places (inconsistent within the same file)

We should
- reformat the whole codebase in a single commit, using a standard formatter and format
- add guidelines somewhere

**Comment by gdfm** [comment]
I am moving the code to the git repo of the ASF. Now it's a good time to apply the reformatting before we start forking the ASF repo.

**Comment by matthieumorel** [comment]
There seems to be some issues with the repo migration. I'll wait until this is complete and submit the patch then (on the apache/incubator-samoa github repo image).

**Comment by gdfm** [comment]
Yeah, I hope to be done soon. Thanks!

**Comment by smarthi** [comment]
Some Machine Learning projects have been following the convention of 2 spaces indent for each level like in Mahout (http://mahout.apache.org) and Oryx (http://github.com/oryxproject/oryx).  I think that should keep Samoa consistent with the other ML projects.

**Comment by gdfm** [comment]
Thanks, let's move the discussion over to the Apache Jira https://issues.apache.org/jira/browse/SAMOA-6
I'll be closing this ticket.
