### ISSUE TITLE
Adaptive Sliding window model to read tweets

### ISSUE THREAD

**Issue by ambodi** [yahoo/samoa#126]
I wanna read tweets from twitterAPI and I would like to keep them in an arraylist or list until they are processed. Now the problem is the window size, of course. I wanna keep let's say 5000 instances. But that number is fixed, I want it to be adaptive to where there are no incoming instaces to be maybe 10. 

I know about ADWIN but ADWIN seems to accept inputs as doubles which in our case is objects. Like Twitter Objects. Is that achievable with ADWIN or other available Windowing solutions in SAMOA? If so, how.

**Comment by abifet** [comment]
ADWIN keeps a sliding window of double numbers that correspond to the
current distribution of data. In your case, if you need to keep a sliding
window of tweets, maybe using a list should be enough.

**Comment by gdfm** [comment]
What is the rule for deciding the size of the window?
If it is time, maybe a cache from Guava could be helpful.
To use ADWIN you need some other statistical property of the data to use.
