### ISSUE TITLE
Disambiguate ArffFileStream

### ISSUE THREAD

**Issue by gdfm** [yahoo/samoa#127]
Right now we have 2 ArffFileStream classes.
One in com.yahoo.labs.samoa.streams and another one in com.yahoo.labs.samoa.moa.streams.

I think we should keep only the first one and get rid of the second one if it's not used.

**Comment by smarthi** [comment]
Both of them r not being used anywhere presently. Which one do we wanna retain?

**Comment by gdfm** [comment]
At least one of the two is being used, even though not statically from the codebase. When you launch SAMOA from the command line, e.g.:
`bin/samoa local target/SAMOA-Local-0.0.1-SNAPSHOT.jar "PrequentialEvaluation -l classifiers.ensemble.Bagging -s (ArffFileStream -f covtypeNorm.arff) -f 100000"`
you are instantiating an InstanceStream (the -s option).
Given that InstanceStream is in com.yahoo.labs.samoa.moa.streams, right now we are using com.yahoo.labs.samoa.moa.streams.ArffFileStream.
However com.yahoo.labs.samoa.stream.ArffFileStream is the new one with the new class architecture. This ArffFileStream extends FileStream and should allow to read several file formats.
