### ISSUE TITLE
How to create a Clustering task

### ISSUE THREAD

**Issue by amoriam** [yahoo/samoa#135]
Hello,

I'm trying to create a clustering task using the streamKM++. I am not sure how to write the command, in the SAMOA documentation (https://samoa.incubator.apache.org/documentation/Distributed-Stream-Clustering.html) it says: (bin/samoa storm target/SAMOA-Storm-0.0.1-SNAPSHOT.jar "ClusteringEvaluation") but, shouldn't it be "ClusteringTask" instead of "ClusteringEvaluation"?
I tried both and wrote something like this which didn't work:
bin/samoa storm target/SAMOA-Storm-0.3.0-SNAPSHOT.jar "ClusteringEvaluation -d /opt/testdump/dump.csv -l (com.yahoo.labs.samoa.learners.clusterers.ClustreamClustererAdapter) -s (com.yahoo.labs.samoa.moa.streams.clustering.RandomRBFGeneratorEvents)"

Can anyone please tell me how to perform  a clustering  task?

Thank you

**Comment by abifet** [comment]
Hi,

In SAMOA you need to use "ClusteringEvaluation". You may start trying with
the simplest setting:

git clone http://git.apache.org/incubator-samoa.git
cd incubator-samoa
mvn package

bin/samoa local target/SAMOA-Local-0.3.0-SNAPSHOT.jar "ClusteringEvaluation
-d dump.csv -i 100000 -f 10000"

Cheers,

Albert

**Comment by amoriam** [comment]
I tried that and it worked, thanks Alberta!
So, if I were to apply streamKM++ on the Iris data. How do I point to the input data to be clustered and the clustering results' output file? could you write down the command please. I thought that -i/-o were to point to the input/output files. 

Thanks you,

Amr

**Comment by gdfm** [comment]
Hi,
I would encourage you to continue this discussion on the official Apache repository for SAMOA.
http://github.com/apache/incubator-samoa
As stated on the main page, this repository has been discontinued and will no longer be supported.
