### ISSUE TITLE
MaxInstanceLimit parameter (-i) problem of PrequentialEvaluation Task 

### ISSUE THREAD

**Issue by l0huan08** [yahoo/samoa#55]
PrequentialEvaluation Task has a "-i" parameter which means the max number of training/test instances. The source code shows when -i = -1, it means unlimited training/test instances, but when I entered -1 for this parameter(-i), the samoa program behave as same as -i=0, that no instance will be sent for training and test.

Enter:
hl@hlnode4:/opt/samoa$ /opt/samoa/bin/samoa local target/SAMOA-Local-0.0.1-SNAPSHOT.jar "PrequentialEvaluation -i -1 -f 500"

Running Output:
none

The correct output should be as below:
classified instances = 500
classifications correct (percent) = 63
Kappa Statistic (percent) = -0.504
Kappa Temporal Statistic (percent) = 24.797
[main] INFO com.yahoo.labs.samoa.evaluation.EvaluatorProcessor - 0 seconds for 500 instances
[main] INFO com.yahoo.labs.samoa.evaluation.EvaluatorProcessor - evaluation instances = 1,000
classified instances = 1,000
classifications correct (percent) = 62.3
Kappa Statistic (percent) = -0.266
Kappa Temporal Statistic (percent) = 21.622
...
...

and keep runing

**Comment by gdfm** [comment]
Ported to [SAMOA-32](https://issues.apache.org/jira/browse/SAMOA-32).
